### ISSUE TITLE
想问一下，我的配置除了无线网卡和大佬的全部都一样，可以使用吗

### ISSUE THREAD

**Issue by qingweia** [imzhengziyi/ASRock-B365M-ITX-AC-opencore-macOS-10.15#1]
无线网卡的efi需不需要处理下？

**Comment by imzhengziyi** [comment]
不处理可以使用有线网络，板载的WiFi和蓝牙不能使用，在config中修改启用BrcmBluetoothInjector.kext，可以驱动板载蓝牙，板载WiFi可以找远景内的Intel驱动使用

**Comment by qingweia** [comment]
感谢大佬！另外没有核显可以开启独显加速吗，我看远景上说可以手动修改oc文件使它支持独显开启加速，目前想装最新的10.15.6，不知道是否可行？oc文件支持吗？

**Comment by imzhengziyi** [comment]
1. 可以随意升级到10.15.6，全新安装不知道是否可以引导，你可以试试，我的免驱显卡蓝宝石RX570 4G目前已经双硬解了，方法是下载我本仓库最新的OC配置文件，编辑config文件，在里面去掉WhateverGreen.kext和MacProMemoryNotificationDisabler.kext就可以了。
2. 我机型使用的是iMacPro7,1，OC里默认的好像也是这个机型，是的话就不用修改；目前的问题是开机过程中会有几个很小的紫点一闪而过，很小的不影响美观，开机后会提示内存错误，点击一下就没有提示了。
3. MacProMemoryNotificationDisabler.kext可以屏蔽内存错误提示，但是它依赖WhateverGreen.kext，不推荐使用

**Comment by imzhengziyi** [comment]
推荐自己使用GenSMBIOS生成机型的序列号等信息，地址：https://github.com/imzhengziyi/Hackintosh-tools

避免和之前已经下载但没有修改序列号的人冲突

**Comment by qingweia** [comment]
试了一下午，用您的oc一直显示禁止安装。换了很多驱动都不行。
后来试了另外一个clover成功安装了，可是驱动不全，所以现在正在尝试替换为您的这份oc。

**Comment by imzhengziyi** [comment]
是的，clover引导安装好系统之后换OC就可以了

**Comment by qingweia** [comment]
基本都搞定啦，但是最后遇到了点问题，我看教程上最后一步是复制efi进系统硬盘的的efi，然后再用uefi添加启动项，我添加完每次重启都没有oc的界面，会直接到Windows系统，去bios看也没有oc的启动项。。
搞了一晚上了，大佬有什么提示吗

**Comment by imzhengziyi** [comment]
在macOS里挂载EFI分区，直接把EFI文件替换原来的EFI重启就可以了，不知道你的双系统是在一个硬盘上还是2个硬盘上，OC会自动扫描各个硬盘上的EFI分区，例如我的主硬盘nvme是Windows10 ，硬盘上有个EFI分区，SATA硬盘装的macOS，有个EFI分区，我的是SATA硬盘上的EFI为OC，启动时选择SATA硬盘启动，开机时有菜单选择Windows还是macOS

**Comment by qingweia** [comment]
哈哈，非常感谢！
其实我上一段刚发出来就成功了，莫名其妙的。。
但是我的是9400f+590显卡，用fcpx时剪辑一点不卡，但是导出的时候cpu满载而显卡一点不动纯围观。
双加速我按照您上面的说法成功开启的，但是导出显卡不动是我没想到的，导出1080p的10分钟视频都超慢=_=

**Comment by imzhengziyi** [comment]
fcpx剪辑我没测试过，但我使用VideoProc转码时，显卡是全速运转，CPU占用率极地的，你可以尝试论坛里的魔改WhateverGreen.kext

**Comment by qingweia** [comment]
这个貌似无解，必须要核显才能够加速导出，我翻遍了论坛和github都没有解决方法，无核显的u导出都是挺慢的。
另外我试着没有删除WhateverGreen.kext和MacProMemoryNotificationDisabler.kext这两个也可以免驱双加速了。
最后，重启还是掉mac的引导...刚才重启mac的引导又不见了。。。可能是因为我是一个盘装的双系统？
..

**Comment by imzhengziyi** [comment]
一个盘装的双系统理论上也是没有问题的吧，这个我不太清楚，建议看看这个地址的教程测试 http://imacos.top/2020/04/06/1559/
，我并不是单硬盘所以不太清楚

qingweia <notifications@github.com> 于2020年7月24日周五 下午3:42写道：

**Comment by qingweia** [comment]
非常感谢你的指导，现在基本完美使用啦，因为我不用无线所以没换网卡。
唯一遗憾的就是usb3.0只有2.0的速度，不过无关大雅。

**Comment by imzhengziyi** [comment]
这主板本身除了内置的USB，其他都是USB3.0，你可以USB定制解决问题，也是很简单的
定制了USB后不能修改机型，否则开机USB不能使用
