### ISSUE TITLE
请问你有这问题吗

### ISSUE THREAD

**Issue by qingweia** [imzhengziyi/ASRock-B365M-ITX-AC-opencore-macOS-10.15#2]
你好大佬！
我最近用了一段时间您的配置，以及其他朋友分享的efi，但是发现都有同样的问题，那就是用网页看流媒体的时候会时不时花屏，同时声音也会不同步。当我用chrome把硬件加速关掉以后就正常了。
换了基本全网所有的本配置efi都有这问题，具体配置是9400F+590 不适用蓝牙和wifi。
我尝试打上A卡的修复驱动也没有用。
请问你有这问题吗，我不太清楚是不是我个例，自己的显卡原因。
感谢！~

**Comment by imzhengziyi** [comment]
我没有遇到此问题，OC在我的机器上完美运行，游戏 网页视频均正常，你可以尝试去掉WhateverGreen.kext
<https://github.com/imzhengziyi/ASRock-B365M-ITX-AC-opencore/tree/master/EFI/OC/Kexts/WhateverGreen.kext/Contents>
试试，另外USB全部为2.0是因为没有USB定制，因为我的机箱没有前置USB接口，所以OC里我没有定制USB，你自己定制后就正常了

qingweia <notifications@github.com> 于2020年7月31日周五 下午7:05写道：
